[package]
name = "mailgun_v3"
version = "0.1.0"
authors = ["Nathan Merritt <nathan@gnmerritt.net>"]

[dependencies]
chrono = "0.4.5"
reqwest = "0.8.7"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
